Add Mqtt status display
rneventteknik/backstage2 pull request #19
Opened 2024-02-25 22:02 UTC by seam0untain

Testar att göra en pr med status utkast. Lite detaljer återstår men konceptet håller

![bild](https://github.com/rneventteknik/backstage2/assets/160432239/6f1a1302-8a02-4b10-9500-0bdc760836e9)

2024-02-25 22:14 UTC, m4reko commented
Snyggt! Frågan är hur mycket vi vill bryta ut till systeminställningar. Vore ju snyggt om vi kunde bygga det så generellt att det går att lägga till flera topics från inställningarna men det kanske kostar mer än vad det smakar.

Vad är kvar att lösa?

2024-02-26 13:44 UTC, gingemarsson commented
Snyggt! Tänker dock på `NEXT_PUBLIC_MQTT_BROKER_PASS`, genom att lägga den som NEXT_PUBLIC kan man nog komma åt det även om man inte är inloggad eftersom de skickas med till alla sidor, inklusive de utan auth. Kanske vore bättre att hämta dem via en endpoint som kollar att man är inloggad?

2024-02-26 20:39 UTC, seam0untain commented
> Snyggt! Frågan är hur mycket vi vill bryta ut till systeminställningar. Vore ju snyggt om vi kunde bygga det så generellt att det går att lägga till flera topics från inställningarna men det kanske kostar mer än vad det smakar.
> 
> Vad är kvar att lösa?

Tycker det är rätt skönt att detta som inte tillhör kärnfunktionalitet är ganska självständigt. Ska man göra något generellt med systeminställningarna kräver det ju att allt följer mönstret vilket inte alltid är sant.

Publik broker och verifiera att meddelandestrukturen håller.

2024-02-26 20:49 UTC, seam0untain commented
> Snyggt! Tänker dock på `NEXT_PUBLIC_MQTT_BROKER_PASS`, genom att lägga den som NEXT_PUBLIC kan man nog komma åt det även om man inte är inloggad eftersom de skickas med till alla sidor, inklusive de utan auth. Kanske vore bättre att hämta dem via en endpoint som kollar att man är inloggad?

Snyggt fångat! Vad jag vet inlinar den variablen under bygget. Tror det är OK men det är lite på gränsen.
Om vi ändå ska göra en endpoint kikar jag gärna på något tokenbaserat.

2024-08-04 18:00 UTC, gingemarsson requested changes
Great job! I have some minor suggestions for improvements, but I think it looks really good in general 😊

I'm on mobile through, so I haven't had the opportunity to test run it yet.

2024-08-29 18:04 UTC, m4reko commented
The meeting wants:
- More text to describe what the icons mean
- The card should be moved to top right home page

2025-06-18 20:27 UTC, merged